name: WordsRepository

on:
  pull_request:
    paths:
      - "packages/words_repository/**"
      - ".github/workflows/words_repository.yaml"

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/dart_package.yml@v1
    with:
      coverage_excludes: "*.g.dart"
      dart_sdk: "stable"
      working_directory: "packages/words_repository"
